# Generated by Django 2.2 on 2019-04-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_food.MealCategory'),
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_food.Department'),
        ),
    ]
