# Generated by Django 2.2 on 2019-04-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0003_servicepercentage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='crm_food.MealCategory'),
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mealcategories', to='crm_food.Department'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isitopen', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('meal', models.ManyToManyField(null=True, related_name='orders', to='crm_food.Meal')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_food.Status')),
                ('table', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_food.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_sum', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_food.Order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_food.ServicePercentage')),
            ],
        ),
    ]
