# Generated by Django 2.2 on 2019-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0004_auto_20190409_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.ManyToManyField(related_name='orders', to='crm_food.Meal'),
        ),
    ]
