# Generated by Django 2.2 on 2019-05-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food', '0008_auto_20190414_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountMeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countmeal', to='crm_food.Meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countmeal', to='crm_food.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.ManyToManyField(related_name='orders_count', through='crm_food.CountMeals', to='crm_food.Meal'),
        ),
    ]
